version: "1"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - gocyclo
    - dupl
    - goconst
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gocognit
    - godot
    - godox
    - funlen
    - whitespace
    - goprintffuncname
    - gomnd
    - goerr113
    - gomodguard
    - asciicheck
    - durationcheck
    - exportloopref
    - forcetypeassert
    - makezero
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - wastedassign
