run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    # Ignore defer statements for these functions as they're commonly
    # used for cleanup and error handling is optional
    exclude-functions:
      - (*os.File).Close
      - (*os.File).Write
      - (*os.File).WriteString
      - (io.Closer).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment # Don't worry about struct field alignment
      - shadow # Allow shadow variables in tests and CLI

issues:
  exclude-rules:
    # Exclude defer close and cleanup functions from errcheck
    - linters:
        - errcheck
      text: "Error return value of.*(?:Close|RemoveAll|Remove).*is not checked"

    # Allow unused parameters in test files
    - path: _test\.go
      linters:
        - unused
        - deadcode

    # Allow shadow variables (common in error handling)
    - linters:
        - govet
      text: "shadow:"
