run:
  timeout: 10m
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gosec
  disable:
    - varnamelen
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits

linters-settings:
  errcheck:
    # Lista de funciones para ignorar errores de retorno
    exclude-functions:
      # File operations commonly used with defer
      - (*os.File).Close
      - (*os.File).Sync
      - (io.Closer).Close
      # Cleanup functions where errors are typically ignored
      - os.Remove
      - os.RemoveAll
      - (*os.File).Write
      - (*os.File).WriteString

  govet:
    enable-all: true
    disable:
      - fieldalignment # Don't worry about struct field alignment
      - shadow # Allow shadow variables

  gosec:
    excludes:
      - G306 # Expect WriteFile permissions to be 0600 or less (we use 0644 intentionally)

  misspell:
    # Ignore Spanish words in comments
    ignore-words:
      - comandos
      - comando
      - argumentos

issues:
  # Lista de patrones para excluir
  exclude-rules:
    # Ignorar errcheck en defer cleanup
    - linters:
        - errcheck
      text: "Error return value of .*(Close|Remove|RemoveAll|Sync) is not checked"

    # Permitir variables no usadas en archivos de test
    - path: _test\.go
      linters:
        - unused
        - deadcode

    # Ignorar algunos problemas de seguridad en tests
    - path: _test\.go
      linters:
        - gosec

  # Excluir archivos específicos si es necesario
  exclude-files:
    - "vendor/.*"

  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0

  # Show only new issues created after git revision
  new: false

# Simplified output configuration for compatibility
# output:
#   format: colored-line-number
