# Example configuration for a Rust project
name: rust-project
container-provider: docker
image: rust:1.75-alpine
pre-install:
  - apk add --no-cache git curl bash musl-dev
  - rustup component add clippy rustfmt
shell:
  init-hook:
    - echo "Rust development environment initialized"
    - rustc --version
    - cargo --version
  scripts:
    - name: test
      description: "Run Rust tests"
      commands:
        - echo "Running Rust tests..."
        - cargo test
    - name: build
      description: "Build the Rust project in debug mode"
      commands:
        - cargo build
    - name: release
      description: "Build the Rust project in release mode"
      commands:
        - cargo build --release
    - name: run
      description: "Run the Rust application"
      commands:
        - cargo run
    - name: lint
      description: "Run Clippy linter"
      commands:
        - cargo clippy -- -D warnings
    - name: format
      description: "Format Rust code"
      commands:
        - cargo fmt
    - name: check
      description: "Check code for errors without building"
      commands:
        - cargo check
    - name: update
      description: "Update dependencies"
      commands:
        - cargo update
    - name: clean
      description: "Clean build artifacts"
      commands:
        - cargo clean
    - name: doc
      description: "Generate and open documentation"
      commands:
        - cargo doc --open
