name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          if [ -z "${GPG_PRIVATE_KEY:-}" ]; then
            echo "GPG_PRIVATE_KEY not set; skipping GPG import."
            exit 0
          fi
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          printf '%s' "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
          echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
          gpg --list-secret-keys --keyid-format=long

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
